"""Generate a public, synthetic PDF fixture using the production BRC1 writer.

Run from backend: PYTHONPATH=. .venv/bin/python tools/generate_reader_fixture.py
All keys/nonces below are deterministic TEST DATA, never production secrets.
"""

import base64
import io
import tempfile
import uuid
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch

from fastapi import UploadFile

from src import storage


def sample_pdf() -> bytes:
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] "
        b"/Resources << /Font << /F1 7 0 R >> >> /Contents 4 0 R >>",
        b"",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] "
        b"/Resources << /Font << /F1 7 0 R >> >> /Contents 6 0 R >>",
        b"",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    for index, page in [(3, 1), (5, 2)]:
        stream = f"BT /F1 18 Tf 30 150 Td (Protected page {page}) Tj ET\n".encode()
        objects[index] = (
            f"<< /Length {len(stream)} >>\nstream\n".encode() + stream + b"endstream"
        )
    result = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, 1):
        offsets.append(len(result))
        result.extend(f"{index} 0 obj\n".encode() + obj + b"\nendobj\n")
    xref = len(result)
    result.extend(f"xref\n0 {len(offsets)}\n0000000000 65535 f \n".encode())
    for offset in offsets[1:]:
        result.extend(f"{offset:010} 00000 n \n".encode())
    result.extend(
        f"trailer\n<< /Size {len(offsets)} /Root 1 0 R >>\n"
        f"startxref\n{xref}\n%%EOF\n".encode()
    )
    return bytes(result)


def main() -> None:
    key = bytes(range(32))
    version = uuid.UUID("00000000-0000-0000-0000-000000000001")
    plain = sample_pdf()
    with tempfile.TemporaryDirectory() as directory:
        test_settings = replace(storage.settings, storage_root=Path(directory))
        test_settings.__dict__["book_kek"] = bytes([255]) * 32
        with (
            patch.object(storage, "settings", test_settings),
            patch.object(storage, "CHUNK_SIZE", 128),
            patch.object(storage.AESGCM, "generate_key", return_value=key),
            patch.object(
                storage.os, "urandom", side_effect=[bytes([i]) * 12 for i in range(1, 32)]
            ),
        ):
            encrypted = storage.encrypt_pdf(
                UploadFile(filename="fixture.pdf", file=io.BytesIO(plain)), version
            )
        container = (Path(directory) / encrypted.storage_path).read_bytes()
    output = Path(__file__).resolve().parents[2] / "bookino-app/test/fixtures/backend_pdf.dart"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "// Generated by backend/tools/generate_reader_fixture.py. Public test data only.\n"
        f"const fixtureVersionId = '{version}';\n"
        "const fixtureChunkSize = 128;\n"
        f"const fixtureKey = '{base64.b64encode(key).decode()}';\n"
        f"const fixturePdf = '{base64.b64encode(plain).decode()}';\n"
        f"const fixtureContainer = '{base64.b64encode(container).decode()}';\n"
    )
    print(f"Generated {output.name}: {len(plain)} PDF bytes, {len(container)} protected bytes")


if __name__ == "__main__":
    main()
